### ISSUE TITLE
enhancement Top1000

### ISSUE THREAD

**Issue by ValentinJesse** [Zhangxi-Lam/alfred-cryptocurrency#1]
You can use this to list the top 1000 coins instead of the top 100

https://api.coinmarketcap.com/v1/ticker/?start=0&limit=1000

or 

https://api.coinmarketcap.com/v1/ticker/?start=0&limit=0

to list everything

**Comment by Zhangxi-Lam** [comment]
Thanks for your comment. I might do it this weekend.

**Comment by Zhangxi-Lam** [comment]
Updated the workflow. Please check the second release :)
